### PR TITLE
Fabric 1.20.1 Create 6.0.7

### LINKED ISSUE #767: Funnels don't extract from Rolling Mill
**Describe the bug**
If you have a rolling mill on a belt with 2 funnels, as shown in the ponder screen, the funnel meant to take items out does nothing. Instead, the result is just stuck inside the rolling mill until you either right click it to take the item out, or remove the exit funnel.

Video showing it:
https://www.youtube.com/watch?v=sYmOdCsenZI

**To Reproduce**
1. Place a rolling mill on a moving belt with an intake and outtake funnel.
2. Have an item inserted and processed.
3. Item does not leave the mill as long as the outtake funnel is there.

**Additional context**
- Mod version: 1.2.3 (Fabric)
- Fabric Loader: 0.15.7
- Fabric API: 0.92.0
- Create version: 0.5.1-f-build.1335

*edit:* 
To add, tested with just Create, CC&A and Fabric API, no other mods.

### LINKED ISSUE #948: Portable Energy Interface has no Graphic for Extending Connecter when not on a contraption. (Create V6.0.4, Crafts V1.3.1, Forge 47.4.0)
The Portable Energy interface has no graphic show up for the Extending Connecter. It does show up when it is added to a formed contraption and still does function just fine on a contraption or not, however its graphic still doesn't show up even when it is connected to a contraption.

Image

### LINKED ISSUE #1078: Update fabric version
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: the newest fabric port update to create wont work with this important mod can you plz make it compatable with the update it came 30 mins ago
**Additional context**
- Mod version:1.20.1
- Fabric version:0.17.2
- Create version:6.0

### PR DESCRIPTION
**Pull request by LaMalditaG**
## Pull Request Checklist

- [x] I have thoroughly tested the changes and verified they work as expected.
- [x] The code follows the coding standards and best practices of the project.
- [x] I have reviewed the changes for potential security or performance issues.

## MIT License Confirmation

- [x] I confirm that all code included in this PR is compatible with the [MIT License](https://opensource.org/licenses/MIT).
- [x] I understand and accept that, by submitting this pull request, all contributions are permanently licensed under the MIT License, and I waive any rights to revoke or change the license in the future.

## Description

Ported to Create 6.0.7
- Dependencies
  - Update Create dependency
  - Added Flywheel and Ponder
  - Updated Loom
  - Updated Fabric loader and api
- Update Code
  - Updated class references to fit with the new Create api
  - Other small refactors
- Added electrum block
- Updated language files
- Bugs
  - Portable Eenergy Interface is now correctly rendered
  - Rolling Mill output funnel now works the same way as in the Forge version

## Related Issues
fixes #767 
fixes #948 in Fabric
closes #1078

### CODE REVIEW

**Comment by FireRat666** [comment]
Not sure where I should put this but I tried building your fork and it seems to work for single player but not on my multiplayer server for some reason

```
[12:23:56] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition' at 'com.mrh0.createaddition.CreateAddition'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:409) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:407) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.17.2.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.2.jar:?]
Caused by: java.lang.NoClassDefFoundError: dev/engine_room/flywheel/api/visual/Visual
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:165) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:368) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:231) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.17.2.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at com.mrh0.createaddition.index.CABlocks.<clinit>(CABlocks.java:163) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at com.mrh0.createaddition.index.CACreativeModeTabs.lambda$static$0(CACreativeModeTabs.java:25) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at io.github.fabricators_of_create.porting_lib.util.RegistryObject.get(RegistryObject.java:65) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.lambda$register$0(LazyRegistrar.java:72) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:71) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at com.mrh0.createaddition.index.CACreativeModeTabs.register(CACreativeModeTabs.java:31) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at com.mrh0.createaddition.CreateAddition.onInitialize(CreateAddition.java:67) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405) ~[fabric-loader-0.17.2.jar:?]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: dev.engine_room.flywheel.api.visual.Visual
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:239) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.17.2.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:165) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:368) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:231) ~[fabric-loader-0.17.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.17.2.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at com.mrh0.createaddition.index.CABlocks.<clinit>(CABlocks.java:163) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at com.mrh0.createaddition.index.CACreativeModeTabs.lambda$static$0(CACreativeModeTabs.java:25) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at io.github.fabricators_of_create.porting_lib.util.RegistryObject.get(RegistryObject.java:65) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.lambda$register$0(LazyRegistrar.java:72) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:71) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at com.mrh0.createaddition.index.CACreativeModeTabs.register(CACreativeModeTabs.java:31) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at com.mrh0.createaddition.CreateAddition.onInitialize(CreateAddition.java:67) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405) ~[fabric-loader-0.17.2.jar:?]
        ... 6 more
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
```

Seems to be caused by flywheel? 
Thank you for putting the work in to update the mod, I would not be able to do it myself 

I am not sure if it's helpful at all but AI says "It seems like you're running into a server-side crash with the Create Addition mod. The error java.lang.NoClassDefFoundError: dev/engine_room/flywheel/api/visual/Visual suggests that the mod is trying to use a client-side rendering class (from the Flywheel library) on the server, where it isn't available."
and "The build.gradle file confirms that createaddition declares a dependency on Flywheel. The problem is that it's using modImplementation, which bundles the dependency for both the client and the server. Flywheel is a client-side rendering library, so it shouldn't be on the server."

**Comment by LaMalditaG** [comment]
It seems that the AI is right in this one. However I'm not getting that error for some reason. In any case it should be fixed now

**Comment by FireRat666** [comment]
I tried your fix, the update to the build.gradle but it is still not working for me and crashing with the same error
I have been trying to get AI to help me fix it so I don't need to bother anyone else but I've not had any success 

> The fact that the NoClassDefFoundError for dev/engine_room/flywheel/api/visual/Visual persists even after correctly configuring modCompileOnly and rebuilding the mod points to a deeper problem within the createaddition mod's code itself.
> The stack trace clearly shows the error originating from: at com.mrh0.createaddition.index.CABlocks.<clinit>(CABlocks.java:163) at com.mrh0.createaddition.index.CACreativeModeTabs.lambda$static$0(CACreativeModeTabs.java:25) at com.mrh0.createaddition.CreateAddition.onInitialize(CreateAddition.java:67)
> This indicates that during the static initialization of CABlocks (which happens very early when the mod loads), it's attempting to access a client-side Flywheel class (Visual). Even with modCompileOnly, if the code path is executed on the server, and that code path directly references a client-only class, it will crash. This is a common issue when client-side rendering logic isn't properly separated from common (client/server) initialization code.
> 
> The stack trace clearly points to CABlocks.<clinit>(CABlocks.java:163) as the origin of the NoClassDefFoundError. This means that during the static initialization of the CABlocks class (which happens when the server starts), it's trying to access a class from Flywheel (dev/engine_room/flywheel/api/visual/Visual) that only exists on the client.
> This is a common issue in Fabric/Forge development where client-specific code isn't properly separated or guarded from server-side execution. To fix this, we need to modify CABlocks.java to ensure that any client-only references are only made when running on the client.

it first wanted to uncomment the lines you had commented out, then change modImplementation to modCompileOnly
I am not sure what it is and why you are not able to replicate it but there are a lot of mods on the server, maybe that is why

```
        - ae2 15.4.10
           \-- team_reborn_energy 3.0.0
        - appleskin 2.5.1+mc1.20
        - architectury 9.2.14
        - balm 7.3.37
           \-- kuma_api 20.1.12
        - beekeeperhut 2.0.1
        - bettercaves 1.20.1-Fabric-2.0.5
           \-- org_reflections_reflections 0.10.2
        - betterdeserttemples 1.20-Fabric-3.0.3
        - betterdungeons 1.20-Fabric-4.0.4
        - betterendisland 1.20-Fabric-2.0.6
        - betterfortresses 1.20-Fabric-2.0.6
        - betterjungletemples 1.20-Fabric-2.0.5
        - bettermineshafts 1.20-Fabric-4.0.4
        - betteroceanmonuments 1.20-Fabric-3.0.4
        - betterstrongholds 1.20-Fabric-4.0.3
        - betterwitchhuts 1.20-Fabric-3.0.3
        - bosses_of_mass_destruction 1.7.5-1.20.1
           |-- maelstrom_library 1.6.1-1.20
           \-- multipart_entities 1.5-1.20
        - c2me 0.2.0+alpha.11.16
           |-- c2me-base 0.2.0+alpha.11.16
           |-- c2me-client-uncapvd 0.2.0+alpha.11.16
           |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.16
           |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.16
           |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.16
           |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.16
           |-- c2me-notickvd 0.2.0+alpha.11.16
           |-- c2me-opts-allocs 0.2.0+alpha.11.16
           |-- c2me-opts-chunk-access 0.2.0+alpha.11.16
           |-- c2me-opts-chunkio 0.2.0+alpha.11.16
           |-- c2me-opts-math 0.2.0+alpha.11.16
           |-- c2me-opts-scheduling 0.2.0+alpha.11.16
           |-- c2me-opts-worldgen-general 0.2.0+alpha.11.16
           |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.16
           |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.16
           |-- c2me-rewrites-chunkio 0.2.0+alpha.11.16
           |-- c2me-server-utils 0.2.0+alpha.11.16
           |-- c2me-threading-chunkio 0.2.0+alpha.11.16
           |-- c2me-threading-lighting 0.2.0+alpha.11.16
           |-- c2me-threading-worldgen 0.2.0+alpha.11.16
           |-- com_ibm_async_asyncutil 0.1.0
           |-- net_objecthunter_exp4j 0.4.8
           \-- org_threadly_threadly 7.0
        - cardinal-components 5.2.3
           |-- cardinal-components-base 5.2.3
           |-- cardinal-components-block 5.2.3
           |-- cardinal-components-chunk 5.2.3
           |-- cardinal-components-entity 5.2.3
           |-- cardinal-components-item 5.2.3
           |-- cardinal-components-level 5.2.3
           |-- cardinal-components-scoreboard 5.2.3
           \-- cardinal-components-world 5.2.3
        - carryon 2.1.2.7
        - cloth-config 11.1.136
           \-- cloth-basic-math 0.6.1
        - create 6.0.8.0+build.1734-mc1.20.1
           |-- com_google_code_findbugs_jsr305 3.0.2
           |-- flywheel 1.0.5+1.20.1.build.264
           |-- forgeconfigapiport 8.0.0
           |-- milk 1.2.60
           |    \-- dripstone_fluid_lib 3.0.2
           |-- ponder 1.0.91
           |    |-- com_google_code_findbugs_jsr305 3.0.2
           |    |-- flywheel 1.0.0
           |    |-- forgeconfigapiport 8.0.0
           |    \-- javax_annotation_javax_annotation-api 1.3.2
           |-- porting_lib_accessors 2.3.13+1.20.1
           |    \-- porting_lib_core 2.3.13+1.20.1
           |-- porting_lib_base 2.3.13+1.20.1
           |    |-- porting_lib_attributes 2.3.13+1.20.1
           |    |-- porting_lib_common 2.3.13+1.20.1
           |    |-- porting_lib_config 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    |-- porting_lib_fluids 2.3.13+1.20.1
           |    |-- porting_lib_gui_utils 2.3.13+1.20.1
           |    |-- porting_lib_lazy_registration 2.3.13+1.20.1
           |    |-- porting_lib_mixin_extensions 2.3.13+1.20.1
           |    |-- porting_lib_utility 2.3.13+1.20.1
           |    \-- reach-entity-attributes 2.4.0
           |-- porting_lib_brewing 2.3.13+1.20.1
           |    \-- porting_lib_core 2.3.13+1.20.1
           |-- porting_lib_client_events 2.3.13+1.20.1
           |    \-- porting_lib_core 2.3.13+1.20.1
           |-- porting_lib_entity 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    \-- porting_lib_mixin_extensions 2.3.13+1.20.1
           |-- porting_lib_extensions 2.3.13+1.20.1
           |    |-- porting_lib_attributes 2.3.13+1.20.1
           |    |-- porting_lib_common 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    \-- reach-entity-attributes 2.4.0
           |-- porting_lib_model_generators 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    |-- porting_lib_data 2.3.13+1.20.1
           |    |-- porting_lib_model_materials 2.3.13+1.20.1
           |    \-- porting_lib_utility 2.3.13+1.20.1
           |-- porting_lib_models 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    |-- porting_lib_fluids 2.3.13+1.20.1
           |    \-- porting_lib_model_loader 2.3.13+1.20.1
           |-- porting_lib_networking 2.3.13+1.20.1
           |    \-- porting_lib_core 2.3.13+1.20.1
           |-- porting_lib_obj_loader 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    \-- porting_lib_model_loader 2.3.13+1.20.1
           |-- porting_lib_tool_actions 2.3.13+1.20.1
           |    \-- porting_lib_core 2.3.13+1.20.1
           |-- porting_lib_transfer 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    \-- porting_lib_fluids 2.3.13+1.20.1
           |-- reach-entity-attributes 2.4.0
           \-- registrate-fabric 1.3.79-MC1.20.1
                |-- com_google_code_findbugs_jsr305 3.0.2
                \-- porting_lib_tags 3.0
                     \-- porting_lib_gametest 2.1.1090+1.20
        - create_ultimate_factory 2.1.0
        - createaddition 1.2.4
        - entityculling 1.9.3
           |-- transition 1.0.8
           \-- trender 1.0.8
        - exlinefurniture 2.6.3
        - fabric-api 0.92.6+1.20.1
           |-- fabric-api-base 0.4.32+1802ada577
           |-- fabric-api-lookup-api-v1 1.6.37+1802ada577
           |-- fabric-biome-api-v1 13.0.14+1802ada577
           |-- fabric-block-api-v1 1.0.12+1802ada577
           |-- fabric-block-view-api-v2 1.0.3+924f046a77
           |-- fabric-blockrenderlayer-v1 1.1.42+1802ada577
           |-- fabric-client-tags-api-v1 1.1.3+1802ada577
           |-- fabric-command-api-v1 1.2.35+f71b366f77
           |-- fabric-command-api-v2 2.2.14+1802ada577
           |-- fabric-commands-v0 0.2.52+df3654b377
           |-- fabric-containers-v0 0.1.67+df3654b377
           |-- fabric-content-registries-v0 4.0.13+1802ada577
           |-- fabric-convention-tags-v1 1.5.6+1802ada577
           |-- fabric-crash-report-info-v1 0.2.20+1802ada577
           |-- fabric-data-attachment-api-v1 1.0.2+de0fd6d177
           |-- fabric-data-generation-api-v1 12.3.7+1802ada577
           |-- fabric-dimensions-v1 2.1.55+1802ada577
           |-- fabric-entity-events-v1 1.6.1+1c78457f77
           |-- fabric-events-interaction-v0 0.6.5+13a40c6677
           |-- fabric-events-lifecycle-v0 0.2.64+df3654b377
           |-- fabric-game-rule-api-v1 1.0.41+1802ada577
           |-- fabric-item-api-v1 2.1.29+1802ada577
           |-- fabric-item-group-api-v1 4.0.14+1802ada577
           |-- fabric-key-binding-api-v1 1.0.38+1802ada577
           |-- fabric-keybindings-v0 0.2.36+df3654b377
           |-- fabric-lifecycle-events-v1 2.2.23+1802ada577
           |-- fabric-loot-api-v2 1.2.3+1802ada577
           |-- fabric-loot-tables-v1 1.1.47+9e7660c677
           |-- fabric-message-api-v1 5.1.10+1802ada577
           |-- fabric-mining-level-api-v1 2.1.52+1802ada577
           |-- fabric-model-loading-api-v1 1.0.4+1802ada577
           |-- fabric-models-v0 0.4.3+9386d8a777
           |-- fabric-networking-api-v1 1.3.14+a158aa0477
           |-- fabric-networking-v0 0.3.54+df3654b377
           |-- fabric-object-builder-api-v1 11.1.5+e35120df77
           |-- fabric-particles-v1 1.1.3+1802ada577
           |-- fabric-recipe-api-v1 1.0.24+1802ada577
           |-- fabric-registry-sync-v0 2.3.6+1802ada577
           |-- fabric-renderer-api-v1 3.2.2+1802ada577
           |-- fabric-renderer-indigo 1.5.3+85287f9f77
           |-- fabric-renderer-registries-v1 3.2.47+df3654b377
           |-- fabric-rendering-data-attachment-v1 0.3.39+92a0d36777
           |-- fabric-rendering-fluids-v1 3.0.29+1802ada577
           |-- fabric-rendering-v0 1.1.50+df3654b377
           |-- fabric-rendering-v1 3.0.9+1802ada577
           |-- fabric-resource-conditions-api-v1 2.3.9+1802ada577
           |-- fabric-resource-loader-v0 0.11.12+fb82e9d777
           |-- fabric-screen-api-v1 2.0.9+1802ada577
           |-- fabric-screen-handler-api-v1 1.3.33+1802ada577
           |-- fabric-sound-api-v1 1.0.14+1802ada577
           |-- fabric-transfer-api-v1 3.3.6+8dd72ea377
           \-- fabric-transitive-access-wideners-v1 4.3.2+1802ada577
        - fabric-language-kotlin 1.13.7+kotlin.2.2.21
           |-- org_jetbrains_kotlin_kotlin-reflect 2.2.21
           |-- org_jetbrains_kotlin_kotlin-stdlib 2.2.21
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.2.21
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.2.21
           |-- org_jetbrains_kotlinx_atomicfu-jvm 0.29.0
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.10.2
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.10.2
           |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.7.1
           |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.8.0
           |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.8.0
           |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.9.0
           |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.9.0
           \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.9.0
        - fabricloader 0.17.2
           \-- mixinextras 0.5.0
        - faewulf_lib 1.3.2
        - ferritecore 6.0.1
        - flowerymooblooms 2.0.2
        - friendsandfoes 3.0.9
           \-- reach-entity-attributes 2.4.0
        - ftblibrary 2001.2.10
        - ftbultimine 2001.1.7
           \-- reach-entity-attributes 2.4.0
        - geckolib 4.8.2
           \-- com_eliotlash_mclib_mclib 20
        - hexcasting 0.11.2
           \-- serialization_hooks 0.4.99999
        - hexpats 0.1.1-1.20.1
        - immersive_furniture 0.1.2+1.20.1
        - inline 1.20.1-1.2.2
        - jade 11.13.1+fabric
        - java 17
        - jei 15.20.0.118
        - krypton 0.2.3
           \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
        - lithium 0.11.3
        - minecraft 1.20.1
        - modernfix 5.24.4+mc1.20.1
        - moonlight 1.20-2.16.15
        - mr_better_bundle 1.3.2
        - packetfixer 3.3.0
        - patchouli 1.20.1-84.1-FABRIC
           \-- fiber 0.23.0-2
        - paucal 0.6.0+1.20.1-fabric
        - piggyback 1.1.1
        - servercore 1.5.2+1.20.1
           |-- fabric-permissions-api-v0 0.3.1
           |-- org_yaml_snakeyaml 2.2
           |-- placeholder-api 2.1.3+1.20.1
           |-- space_arim_dazzleconf_dazzleconf-core 1.3.0-M2
           \-- space_arim_dazzleconf_dazzleconf-ext-snakeyaml 1.3.0-M2
        - storagedrawers 12.14.3
        - supplementaries 1.20-3.1.41
           \-- mixinsquared 0.1.1
        - terrablender 3.0.1.10
           |-- com_electronwill_night-config_core 3.6.7
           \-- com_electronwill_night-config_toml 3.6.7
        - terralith 2.5.4
        - travelersbackpack 9.1.42
           \-- reach-entity-attributes 2.4.0
        - vivecraft 1.20.1-1.3.4
           |-- com_github_bhaptics_tact-java 0.1.4
           |-- com_illposed_osc_javaosc-core 0.9
           |-- org_java-websocket_java-websocket 1.5.1
           |-- org_lwjgl_lwjgl-openvr 3.3.2
           |-- org_lwjgl_lwjgl-openvr_natives-linux 3.3.2
           |-- org_lwjgl_lwjgl-openvr_natives-macos 3.3.2
           \-- org_lwjgl_lwjgl-openvr_natives-windows 3.3.2
        - voicechat 1.20.1-2.6.6
           |-- fabric-key-binding-api-v1 1.0.36+fb8d95da82
           \-- voicechat_api 2.6.0
        - waystones 14.1.17
        - xaerominimap 25.2.10
        - xaeroworldmap 1.39.12
        - yigd 2.0.16
           \-- libgui 8.1.1+1.20.1
                |-- jankson 6.0.0+j1.2.3
                |    \-- blue_endless_jankson 1.2.3
                \-- libninepatch 1.2.0
        - yungsapi 1.20-Fabric-4.0.6
           \-- org_javassist_javassist 3.29.2-GA
        - yungsbridges 1.20-Fabric-4.0.3
        - yungscavebiomes 1.20.1-Fabric-2.0.5
        - yungsextras 1.20-Fabric-4.0.3
        - yungsmenutweaks 1.20.1-Fabric-1.0.2
```

Also thank you for responding so quickly

**Comment by LaMalditaG** [comment]
this seems to be some compatibility issue with one of the mods you have installed in your server, but at the same time looks that is caused by one of the fixes I added. I'll look into it, but I'll need to see which mod is causing this first

**Comment by skippyall** [comment]
Thank you doing the Create 6 Port. I think we should merge the forge branch into this. For the fix of #948, you could make a PR to the forge branch too.

**Comment by skippyall** [comment]
> It seems that the AI is right in this one. However I'm not getting that error for some reason. In any case it should be fixed now

The dependency on flywheel in the build.gradle is only for the development environment, removing it doesn't have any effect on production. You need to modify the code to actually fix this error

File: src/main/java/com/mrh0/createaddition/CreateAddition.java [hunk 1]
```diff
@@ -9,8 +9,10 @@
 import com.mrh0.createaddition.index.CASounds;
 import com.mrh0.createaddition.network.CANetwork;
 import com.mrh0.createaddition.trains.schedule.CASchedule;
+import com.simibubi.create.api.boiler.BoilerHeater;
+import com.simibubi.create.api.stress.BlockStressValues;
 import com.simibubi.create.content.fluids.tank.BoilerHeaters;
-import com.simibubi.create.content.kinetics.BlockStressValues;
+//import com.simibubi.create.content.kinetics.BlockStressValues;
```
Comment (skippyall) [inline src/main/java/com/mrh0/createaddition/CreateAddition.java]: Don't comment, just remove (same for all other imports).

**Comment by FireRat666** [comment]
> this seems to be some compatibility issue with one of the mods you have installed in your server, but at the same time looks that is caused by one of the fixes I added. I'll look into it, but I'll need to see which mod is causing this first

I am fairly certain the error is caused by Create Addition, the server starts and seems to work perfectly fine without this one mod
AI is also convinced the problem is in the mod, but is not quite good enough to help me fix it 

Edit:

Okay I downloaded Server 1.20.1 from fabricmc 
I tried running the server without createaddition but with all the other mods, Runs fine
I tried running With a minimal amount of mods, create-fabric-6.0.8.0+build.1734-mc1.20.1 and fabric-api-0.92.6-1.20.1
The server runs, But if I add createaddition, so it's just those 3 mod files in the mods folder. I get this error 

```
PS A:\Games\MC\Server1.20.1> java -Xmx2G -jar fabric-server-mc.1.20.1-loader.0.17.3-launcher.1.1.0.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[09:02:38] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.17.3
[09:02:38] [main/INFO]: Loading 83 mods:
        - create 6.0.8.0+build.1734-mc1.20.1
           |-- com_google_code_findbugs_jsr305 3.0.2
           |-- flywheel 1.0.5+1.20.1.build.264
           |-- forgeconfigapiport 8.0.0
           |-- milk 1.2.60
           |    \-- dripstone_fluid_lib 3.0.2
           |-- ponder 1.0.91
           |    |-- com_google_code_findbugs_jsr305 3.0.2
           |    |-- flywheel 1.0.0
           |    |-- forgeconfigapiport 8.0.0
           |    \-- javax_annotation_javax_annotation-api 1.3.2
           |-- porting_lib_accessors 2.3.13+1.20.1
           |    \-- porting_lib_core 2.3.13+1.20.1
           |-- porting_lib_base 2.3.13+1.20.1
           |    |-- com_electronwill_night-config_core 3.6.6
           |    |-- com_electronwill_night-config_toml 3.6.6
           |    |-- porting_lib_attributes 2.3.13+1.20.1
           |    |-- porting_lib_common 2.3.13+1.20.1
           |    |-- porting_lib_config 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    |-- porting_lib_fluids 2.3.13+1.20.1
           |    |-- porting_lib_gui_utils 2.3.13+1.20.1
           |    |-- porting_lib_lazy_registration 2.3.13+1.20.1
           |    |-- porting_lib_mixin_extensions 2.3.13+1.20.1
           |    |-- porting_lib_utility 2.3.13+1.20.1
           |    \-- reach-entity-attributes 2.4.0
           |-- porting_lib_brewing 2.3.13+1.20.1
           |    \-- porting_lib_core 2.3.13+1.20.1
           |-- porting_lib_client_events 2.3.13+1.20.1
           |    \-- porting_lib_core 2.3.13+1.20.1
           |-- porting_lib_entity 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    \-- porting_lib_mixin_extensions 2.3.13+1.20.1
           |-- porting_lib_extensions 2.3.13+1.20.1
           |    |-- porting_lib_attributes 2.3.13+1.20.1
           |    |-- porting_lib_common 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    \-- reach-entity-attributes 2.4.0
           |-- porting_lib_model_generators 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    |-- porting_lib_data 2.3.13+1.20.1
           |    |-- porting_lib_model_materials 2.3.13+1.20.1
           |    \-- porting_lib_utility 2.3.13+1.20.1
           |-- porting_lib_models 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    |-- porting_lib_fluids 2.3.13+1.20.1
           |    \-- porting_lib_model_loader 2.3.13+1.20.1
           |-- porting_lib_networking 2.3.13+1.20.1
           |    \-- porting_lib_core 2.3.13+1.20.1
           |-- porting_lib_obj_loader 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    \-- porting_lib_model_loader 2.3.13+1.20.1
           |-- porting_lib_tool_actions 2.3.13+1.20.1
           |    \-- porting_lib_core 2.3.13+1.20.1
           |-- porting_lib_transfer 2.3.13+1.20.1
           |    |-- porting_lib_core 2.3.13+1.20.1
           |    \-- porting_lib_fluids 2.3.13+1.20.1
           |-- reach-entity-attributes 2.4.0
           \-- registrate-fabric 1.3.79-MC1.20.1
                |-- com_google_code_findbugs_jsr305 3.0.2
                \-- porting_lib_tags 3.0
                     \-- porting_lib_gametest 2.1.1090+1.20
        - createaddition 1.2.4
           \-- team_reborn_energy 2.3.0
        - fabric-api 0.92.6+1.20.1
           |-- fabric-api-base 0.4.32+1802ada577
           |-- fabric-api-lookup-api-v1 1.6.37+1802ada577
           |-- fabric-biome-api-v1 13.0.14+1802ada577
           |-- fabric-block-api-v1 1.0.12+1802ada577
           |-- fabric-block-view-api-v2 1.0.3+924f046a77
           |-- fabric-blockrenderlayer-v1 1.1.42+1802ada577
           |-- fabric-client-tags-api-v1 1.1.3+1802ada577
           |-- fabric-command-api-v1 1.2.35+f71b366f77
           |-- fabric-command-api-v2 2.2.14+1802ada577
           |-- fabric-commands-v0 0.2.52+df3654b377
           |-- fabric-containers-v0 0.1.67+df3654b377
           |-- fabric-content-registries-v0 4.0.13+1802ada577
           |-- fabric-convention-tags-v1 1.5.6+1802ada577
           |-- fabric-crash-report-info-v1 0.2.20+1802ada577
           |-- fabric-data-attachment-api-v1 1.0.2+de0fd6d177
           |-- fabric-data-generation-api-v1 12.3.7+1802ada577
           |-- fabric-dimensions-v1 2.1.55+1802ada577
           |-- fabric-entity-events-v1 1.6.1+1c78457f77
           |-- fabric-events-interaction-v0 0.6.5+13a40c6677
           |-- fabric-events-lifecycle-v0 0.2.64+df3654b377
           |-- fabric-game-rule-api-v1 1.0.41+1802ada577
           |-- fabric-item-api-v1 2.1.29+1802ada577
           |-- fabric-item-group-api-v1 4.0.14+1802ada577
           |-- fabric-key-binding-api-v1 1.0.38+1802ada577
           |-- fabric-keybindings-v0 0.2.36+df3654b377
           |-- fabric-lifecycle-events-v1 2.2.23+1802ada577
           |-- fabric-loot-api-v2 1.2.3+1802ada577
           |-- fabric-loot-tables-v1 1.1.47+9e7660c677
           |-- fabric-message-api-v1 5.1.10+1802ada577
           |-- fabric-mining-level-api-v1 2.1.52+1802ada577
           |-- fabric-model-loading-api-v1 1.0.4+1802ada577
           |-- fabric-models-v0 0.4.3+9386d8a777
           |-- fabric-networking-api-v1 1.3.14+a158aa0477
           |-- fabric-networking-v0 0.3.54+df3654b377
           |-- fabric-object-builder-api-v1 11.1.5+e35120df77
           |-- fabric-particles-v1 1.1.3+1802ada577
           |-- fabric-recipe-api-v1 1.0.24+1802ada577
           |-- fabric-registry-sync-v0 2.3.6+1802ada577
           |-- fabric-renderer-api-v1 3.2.2+1802ada577
           |-- fabric-renderer-indigo 1.5.3+85287f9f77
           |-- fabric-renderer-registries-v1 3.2.47+df3654b377
           |-- fabric-rendering-data-attachment-v1 0.3.39+92a0d36777
           |-- fabric-rendering-fluids-v1 3.0.29+1802ada577
           |-- fabric-rendering-v0 1.1.50+df3654b377
           |-- fabric-rendering-v1 3.0.9+1802ada577
           |-- fabric-resource-conditions-api-v1 2.3.9+1802ada577
           |-- fabric-resource-loader-v0 0.11.12+fb82e9d777
           |-- fabric-screen-api-v1 2.0.9+1802ada577
           |-- fabric-screen-handler-api-v1 1.3.33+1802ada577
           |-- fabric-sound-api-v1 1.0.14+1802ada577
           |-- fabric-transfer-api-v1 3.3.6+8dd72ea377
           \-- fabric-transitive-access-wideners-v1 4.3.2+1802ada577
        - fabricloader 0.17.3
           \-- mixinextras 0.5.0
        - java 17
        - minecraft 1.20.1
[09:02:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/A:/Games/MC/Server1.20.1/libraries/net/fabricmc/sponge-mixin/0.16.5+mixin.0.8.7/sponge-mixin-0.16.5+mixin.0.8.7.jar Service=Knot/Fabric Env=SERVER
[09:02:38] [main/INFO]: Compatibility level set to JAVA_17
[09:02:39] [main/WARN]: Error loading class: net/minecraft/class_881 (java.lang.ClassNotFoundException: net/minecraft/class_881)
[09:02:39] [main/WARN]: @Mixin target net.minecraft.class_881 was not found porting_lib_base.mixins.json:client.BoatRendererMixin from mod porting_lib_base
[09:02:39] [main/WARN]: Error loading class: net/minecraft/class_525 (java.lang.ClassNotFoundException: net/minecraft/class_525)
[09:02:39] [main/WARN]: @Mixin target net.minecraft.class_525 was not found porting_lib_base.mixins.json:client.CreateWorldScreenMixin from mod porting_lib_base
[09:02:39] [main/WARN]: Error loading class: net/minecraft/class_906 (java.lang.ClassNotFoundException: net/minecraft/class_906)
[09:02:39] [main/WARN]: @Mixin target net.minecraft.class_906 was not found porting_lib_tool_actions.mixins.json:FishingHookRendererMixin from mod porting_lib_tool_actions
[09:02:39] [main/WARN]: Error loading class: dev/ftb/mods/ftbchunks/client/gui/LargeMapScreen (java.lang.ClassNotFoundException: dev/ftb/mods/ftbchunks/client/gui/LargeMapScreen)
[09:02:39] [main/WARN]: @Mixin target dev.ftb.mods.ftbchunks.client.gui.LargeMapScreen was not found create.mixins.json:compat.ftbchunks.LargeMapScreenAccessor from mod create
[09:02:39] [main/WARN]: Error loading class: dev/ftb/mods/ftbchunks/client/gui/RegionMapPanel (java.lang.ClassNotFoundException: dev/ftb/mods/ftbchunks/client/gui/RegionMapPanel)
[09:02:39] [main/WARN]: @Mixin target dev.ftb.mods.ftbchunks.client.gui.RegionMapPanel was not found create.mixins.json:compat.ftbchunks.RegionMapPanelAccessor from mod create
[09:02:39] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.5.0).
[09:02:44] [main/INFO]: Create 6.0.8.0 initializing!
[09:02:45] [main/WARN]: Configuration file .\config\createaddition-common.toml is not correct. Correcting
[09:02:45] [main/WARN]: Incorrect key general was corrected from null to its default, SimpleCommentedConfig:{}.
[09:02:45] [main/WARN]: Incorrect key general.fe_at_max_rpm was corrected from null to its default, 240.
[09:02:45] [main/WARN]: Incorrect key general.max_stress was corrected from null to its default, 16384.
[09:02:45] [main/WARN]: Incorrect key general.audio_enabled was corrected from null to its default, true.
[09:02:45] [main/WARN]: Incorrect key electric_motor was corrected from null to its default, SimpleCommentedConfig:{}.
[09:02:45] [main/WARN]: Incorrect key electric_motor.motor_rpm_range was corrected from null to its default, 256.
[09:02:45] [main/WARN]: Incorrect key electric_motor.motor_min_consumption was corrected from null to its default, 8.
[09:02:45] [main/WARN]: Incorrect key electric_motor.motor_max_input was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key electric_motor.motor_capacity was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key alternator was corrected from null to its default, SimpleCommentedConfig:{}.
[09:02:45] [main/WARN]: Incorrect key alternator.generator_max_output was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key alternator.generator_capacity was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key alternator.generator_efficiency was corrected from null to its default, 0.75.
[09:02:45] [main/WARN]: Incorrect key rolling_mill was corrected from null to its default, SimpleCommentedConfig:{}.
[09:02:45] [main/WARN]: Incorrect key rolling_mill.rolling_mill_processing_duration was corrected from null to its default, 120.
[09:02:45] [main/WARN]: Incorrect key rolling_mill.rolling_mill_stress was corrected from null to its default, 8.
[09:02:45] [main/WARN]: Incorrect key wires was corrected from null to its default, SimpleCommentedConfig:{}.
[09:02:45] [main/WARN]: Incorrect key wires.small_connector_max_input was corrected from null to its default, 1000.
[09:02:45] [main/WARN]: Incorrect key wires.small_connector_max_output was corrected from null to its default, 1000.
[09:02:45] [main/WARN]: Incorrect key wires.small_connector_wire_length was corrected from null to its default, 16.
[09:02:45] [main/WARN]: Incorrect key wires.small_light_connector_consumption was corrected from null to its default, 1.
[09:02:45] [main/WARN]: Incorrect key wires.large_connector_max_input was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key wires.large_connector_max_output was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key wires.large_connector_wire_length was corrected from null to its default, 32.
[09:02:45] [main/WARN]: Incorrect key wires.connector_ignore_face_check was corrected from null to its default, true.
[09:02:45] [main/WARN]: Incorrect key wires.connector_allow_passive_io was corrected from null to its default, true.
[09:02:45] [main/WARN]: Incorrect key accumulator was corrected from null to its default, SimpleCommentedConfig:{}.
[09:02:45] [main/WARN]: Incorrect key accumulator.accumulator_max_input was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key accumulator.accumulator_max_output was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key accumulator.accumulator_capacity was corrected from null to its default, 2000000.
[09:02:45] [main/WARN]: Incorrect key accumulator.accumulator_max_height was corrected from null to its default, 5.
[09:02:45] [main/WARN]: Incorrect key accumulator.accumulator_max_width was corrected from null to its default, 3.
[09:02:45] [main/WARN]: Incorrect key portable_energy_interface was corrected from null to its default, SimpleCommentedConfig:{}.
[09:02:45] [main/WARN]: Incorrect key portable_energy_interface.pei_max_input was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key portable_energy_interface.pei_max_output was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key tesla_coil was corrected from null to its default, SimpleCommentedConfig:{}.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_max_input was corrected from null to its default, 10000.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_charge_rate was corrected from null to its default, 5000.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_recipe_charge_rate was corrected from null to its default, 2000.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_capacity was corrected from null to its default, 40000.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_hurt_energy_required was corrected from null to its default, 1000.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_hurt_range was corrected from null to its default, 3.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_hurt_mob was corrected from null to its default, 3.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_effect_time_mob was corrected from null to its default, 20.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_hurt_player was corrected from null to its default, 2.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_effect_time_player was corrected from null to its default, 20.
[09:02:45] [main/WARN]: Incorrect key tesla_coil.tesla_coil_fire_cooldown was corrected from null to its default, 20.
[09:02:45] [main/WARN]: Incorrect key misc was corrected from null to its default, SimpleCommentedConfig:{}.
[09:02:45] [main/WARN]: Incorrect key misc.diamond_grit_sandpaper_uses was corrected from null to its default, 1024.
[09:02:45] [main/WARN]: Incorrect key misc.barbed_wire_damage was corrected from null to its default, 2.0.
[09:02:45] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition' at 'com.mrh0.createaddition.CreateAddition'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:409) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:407) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.17.3.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.17.3-launcher.1.1.0.jar:1.1.0]
Caused by: java.lang.NoClassDefFoundError: dev/engine_room/flywheel/api/visual/Visual
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:165) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:368) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:231) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.17.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at com.mrh0.createaddition.index.CABlocks.<clinit>(CABlocks.java:161) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at com.mrh0.createaddition.index.CACreativeModeTabs.lambda$static$0(CACreativeModeTabs.java:25) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at io.github.fabricators_of_create.porting_lib.util.RegistryObject.get(RegistryObject.java:65) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.lambda$register$0(LazyRegistrar.java:72) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:71) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at com.mrh0.createaddition.index.CACreativeModeTabs.register(CACreativeModeTabs.java:31) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at com.mrh0.createaddition.CreateAddition.onInitialize(CreateAddition.java:67) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405) ~[fabric-loader-0.17.3.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: dev.engine_room.flywheel.api.visual.Visual
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:239) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.17.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:165) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:368) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:231) ~[fabric-loader-0.17.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.17.3.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at com.mrh0.createaddition.index.CABlocks.<clinit>(CABlocks.java:161) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at com.mrh0.createaddition.index.CACreativeModeTabs.lambda$static$0(CACreativeModeTabs.java:25) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at io.github.fabricators_of_create.porting_lib.util.RegistryObject.get(RegistryObject.java:65) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.lambda$register$0(LazyRegistrar.java:72) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at io.github.fabricators_of_create.porting_lib.util.LazyRegistrar.register(LazyRegistrar.java:71) ~[porting_lib_lazy_registration-2.3.13+1.20.1-8dc3c8493b425869.jar:?]
        at com.mrh0.createaddition.index.CACreativeModeTabs.register(CACreativeModeTabs.java:31) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at com.mrh0.createaddition.CreateAddition.onInitialize(CreateAddition.java:67) ~[createaddition-fabric+1.20.1-1.2.4.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405) ~[fabric-loader-0.17.3.jar:?]
        ... 7 more
PS A:\Games\MC\Server1.20.1>
```

**Comment by LaMalditaG** [comment]
So after I little investigation I discovered some things:
- I can replicate the issue, but not in the development environment (runServer gradle task).
- Removing the PEI fixes the issue.
I supposedly fixed an issue with the PEI visuals in the original commit, but it seems that it's more of a problem than a fix.

**Comment by LaMalditaG** [comment]
Alright, it should be fixed now. It was just I little line that I forgot to write that blocked the creation of Visuals on the server. What I don't understand is why it was working in the development environment in the first place

**Comment by FireRat666** [comment]
Thank you very much, it appears to be working for me now

**Comment by skippyall** [comment]
> Thank you doing the Create 6 Port. I think we should merge the forge branch into this. For the fix of #948, you could make a PR to the forge branch too.

Just making sure that doesn't drown

**Comment by LaMalditaG** [comment]
If nobody finds any issue with this PR, I'll gladly open a PR for the PEI issue in the Forge branch

**Comment by mrh0** [comment]
> If nobody finds any issue with this PR, I'll gladly open a PR for the PEI issue in the Forge branch

Yes that would be great!

**Review by mrh0 — APPROVED** [review]
Its not that important but for future reference please just remove unused imports instead of commenting them out. 
Otherwise lgtm, thanks a lot!

**Comment by LaMalditaG** [comment]
> Its not that important but for future reference please just remove unused imports instead of commenting them out. 

Yeah, sorry for that
